### ISSUE TITLE
Can obtain allbadge.dat？

### ISSUE THREAD

**Issue by supernova0003** [AntiMach/allbadge-tool#1]
First of all, thank you to the author for their efforts.I found that there are not only allbadge_v130.dat and_v131.dat, but also another file named allbadge.dat can be obtained.For example,I can download allbadge.dat from the link：https://npdl.cdn.nintendowifi.net/p01/nsa/j0ITmVqVgfUxe0O9/data/allbadge.dat?tm=2. So can we add feature options to the updated version allbadge-tool to obtains official allbadge.dat？

**Comment by AntiMach** [comment]
Sure thing, I had not realized that version existed, thus I had not worried about it. Will work on an update right now.
